FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:80

USER root
RUN mkdir /app/tmp && echo "Velázquez Figueroa Ana María"> /app/tmp/284925.txt
USER app

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["numeroAlumno.csproj", "./"]
RUN dotnet restore "numeroAlumno.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "numeroAlumno.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "numeroAlumno.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "numeroAlumno.dll" ]